@startuml "highlevel"
actor "Website" as Website

component "Api Gateway" as api
component "Service Discovery" as sd
Website -left-> api
api -left-> sd

node Microservices {
    component TweetService
    component ActionService
    component AccountService
    component AuthenticationService
}

cloud "Event Bus" as EventBus

api <-- Microservices
sd <--> Microservices

Microservices --> EventBus

@enduml

@startuml "service"

component api as "API Gateway"
component sd as "Service Discovery"
cloud event as "Event Bus"

component Service as service {
    component Command
    component Query
    component Processor as "Event Processor"
    component "Service Discovery NuGet Library" as sdl
    database "Current State" as state
}


api --> Query : "Get state"
api --> Command : "Perform action"

Command ..> event : TweetPostedEvent
Processor <.. event : Process event

Processor <--> state : Update current state

Query <--> state : Get current state

sdl <-up-> sd : Register & keep alive

@enduml
