@startuml "highlevel"
actor "Website" as Website

component "Api Gateway" as mlb
Website -left-> mlb

node Microservices {
    component TweetService
    component ActionService
    component AccountService
    component AuthenticationService
}

cloud "Event Bus" as EventBus

mlb <--> AuthenticationService
mlb <--> ActionService
mlb <--> TweetService
mlb <--> AccountService

AuthenticationService <..> EventBus
ActionService <..> EventBus
TweetService <..> EventBus
AccountService <..> EventBus

@enduml

@startuml "service"

component api as "API Gateway"
cloud event as "Event Bus"

component Service as service {
    component Command
    component Query
}

database "Current State" as state

api --> Query : "Get state"
api --> Command : "Perform action"

Command ..> event : TweetPostedEvent
Query <.. event : Process

Query <--> state : Update/fetch current state

@enduml
